stack: kontena/openfaas
version: 0.1.0
expose: api
variables:
  app_domain:
    type: string
    default: openfaas.kontena.rocks
    from:
      prompt: Openfaas domain

  monitor_domain:
    type: string
    default: openfaas-monitor.kontena.rocks
    from:
      prompt: Openfaas monitor domain

  master_url:
    type: uri
    schemes:
      - http
      - https
    from:
      prompt: kontena master url

  master_auth_token:
    type: string
    from:
      prompt: kontena master auth token (Bearer token)

  faas_grid:
    type: string
    from:
      prompt: Grid name to use for openfaas

services:
  loadbalancer:
    image: kontena/lb:latest
    secrets:
      - secret: SSL_STAR_kontena_rocks
        name: SSL_CERTS
        type: env
    ports:
      - 80:80
      - 443:443
      - 9090:9090 # TODO maybe can be removed?
  api:
    image: rase/kontena-openfaas:0.0.14
    instances: 1
    stateful: false
    environment:
      - MASTER_URL={{ master_url }}
      - AUTH_TOKEN={{ master_auth_token }}
      - GRID_ID={{ faas_grid }}
    deploy:
      strategy: ha
      wait_for_port: 8080

  gateway:
    instances: 1
    stateful: false
    image: functions/gateway:0.6.1
    links:
      - loadbalancer
      - api:openfaas
    environment:
      - KONTENA_LB_INTERNAL_PORT=8080
      - KONTENA_LB_VIRTUAL_HOSTS={{ app_domain }}
      - functions_provider_url=http://api.openfaas.openfaas.kontena.local:8080
    deploy:
      strategy: ha
      wait_for_port: 8080

  prometheus:
    instances: 1
    stateful: false
    image: rase/openfaas-kontena-prometheus:0.0.1
    command: -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.memory-chunks=10000 --alertmanager.url=http://prometheus-alertmanager.openfaas.kontena.local:9093
    links:
      - loadbalancer
    environment:
      - KONTENA_LB_INTERNAL_PORT=9090
      - KONTENA_LB_VIRTUAL_HOSTS={{ monitor_domain }}
    deploy:
      wait_for_port: 9090

  prometheus-alertmanager:
    instances: 1
    stateful: false
    image: rase/openfaas-kontena-prometheus-alertmanager:0.0.1
    command: -config.file=/alertmanager.yml -storage.path=/alertmanager
    deploy:
      wait_for_port: 9093

# TODO: add NATS
