stack: kontena/openfaas
version: 0.1.0
expose: api
variables:
  app_domain:
    type: string
    default: openfaas.kontena.rocks
    from:
      prompt: Openfaas domain
  functions_provider:
    type: string
    default: kontena-openfaas.openfaas.kontena.local
    from:
      prompt: Openfaas functions provider URL
services:
  loadbalancer:
    image: kontena/lb:latest
    ports:
      - 80:80
  api:
    name: kontena-openfaas
    image: rase-/kontena-openfaas
    instances: 3
    stateful: false
    deploy:
      strategy: ha
      wait_for_port: 8080

  gateway:
    name: openfaas-gateway
    instances: 1
    stateful: false
    image: functions/gateway:0.6.1
    environment:
      - functions_provider_url={{ functions_provider }}
    links:
      - loadbalancer
    environment:
      - KONTENA_LB_INTERNAL_PORT=3000
      - KONTENA_LB_VIRTUAL_HOSTS={{ app_domain }}
    deploy:
      strategy: ha
      wait_for_port: 3000

  prometheus:
    name: openfaas-prometheus
    instances: 1
    stateful: false
    image: rase-/openfaas-prometheus
    deploy:
      wait_for_port: 9090

  prometheus-alertmanager:
    name: openfaas-prometheus-alertmanager
    instances: 1
    stateful: false
    image: rase-/openfaas-prometheus-alertmanager
    deploy:
      wait_for_port: 9093

# TODO: add NATS
