stack: kontena/openfaas
version: 0.1.0
expose: api
variables:
  app_domain:
    type: string
    default: openfaas.kontena.rocks
    from:
      prompt: Openfaas domain

  monitor_domain:
    type: string
    default: openfaas-monitor.kontena.rocks
    from:
      prompt: Openfaas monitor domain

services:
  loadbalancer:
    image: kontena/lb:latest
    secrets:
      - secret: SSL_STAR_kontena_rocks
        name: SSL_CERTS
        type: env
    ports:
      - 80:80
      - 443:443
      - 9090:9090
  api:
    image: rase/kontena-openfaas:0.0.4
    instances: 3
    stateful: false
    environment:
      - MASTER_URL=<fill-here>
      - AUTH_TOKEN=<fill-here>
      - GRID_ID=<fill-here>
    deploy:
      strategy: ha
      wait_for_port: 8080

  gateway:
    instances: 1
    stateful: false
    image: functions/gateway:0.6.1
    links:
      - loadbalancer
      - api:openfaas
    environment:
      - KONTENA_LB_INTERNAL_PORT=8080
      - KONTENA_LB_VIRTUAL_HOSTS={{ app_domain }}
      - functions_provider_url=http://api.openfaas.openfaas.kontena.local:8080
    deploy:
      strategy: ha
      wait_for_port: 8080

  prometheus:
    instances: 1
    stateful: false
    image: rase/openfaas-kontena-prometheus:0.0.1
    links:
      - loadbalancer
    environment:
      - KONTENA_LB_INTERNAL_PORT=9090
      - KONTENA_LB_VIRTUAL_HOSTS={{ monitor_domain }}
    deploy:
      wait_for_port: 9090

  prometheus-alertmanager:
    instances: 1
    stateful: false
    image: rase/openfaas-kontena-prometheus-alertmanager:0.0.1
    deploy:
      wait_for_port: 9093

# TODO: add NATS
