stack: kontena/openfaas
version: 0.1.0
expose: api
variables:
  app_domain:
    type: string
    default: openfaas.kontena.rocks
    from:
      prompt: Openfaas domain
services:
  loadbalancer:
    image: kontena/lb:latest
    secrets:
      - secret: SSL_STAR_kontena_rocks
        name: SSL_CERTS
        type: env
    ports:
      - 80:80
      - 443:443
      - 9090:9090
  api:
    name: kontena-openfaas
    image: rase/kontena-openfaas
    instances: 3
    stateful: false
    deploy:
      strategy: ha
      wait_for_port: 8080

  gateway:
    name: gateway
    instances: 1
    stateful: false
    image: functions/gateway:0.6.1
    environment:
      - functions_provider_url=%{project}-openfaas.kontena.local
    links:
      - loadbalancer
      - kontena-openfaas:openfaas
    environment:
      - KONTENA_LB_INTERNAL_PORT=8080
      - KONTENA_LB_VIRTUAL_HOSTS={{ app_domain }}
    deploy:
      strategy: ha
      wait_for_port: 3000

  prometheus:
    name: prometheus
    instances: 1
    stateful: false
    image: rase/openfaas-prometheus
    links:
      - loadbalancer
    environment:
      - KONTENA_LB_INTERNAL_PORT=9090
      - KONTENA_LB_VIRTUAL_PATH=/prometheus
    deploy:
      wait_for_port: 9090

  prometheus-alertmanager:
    name: prometheus-alertmanager
    instances: 1
    stateful: false
    image: rase/openfaas-prometheus-alertmanager
    deploy:
      wait_for_port: 9093

# TODO: add NATS
