// flow-typed signature: 8b126d9fee8e7a7f83c00c8543c8133c
// flow-typed version: <<STUB>>/url-pattern_v1.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-pattern'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-pattern' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-pattern/lib/url-pattern' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-pattern/lib/url-pattern.js' {
  declare module.exports: $Exports<'url-pattern/lib/url-pattern'>;
}
